#composefile Vesrion ไหน ซึ่งปัจจุบันเป็น Version 3
#ref: https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3'

services: 
  db:
    image: mysql:5.7
    networks: 
      - wordpress
    # docker run --network wordpress
    volumes: 
      - db_data:/var/lib/mysql
    # docker run -v db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 1111
    # docker run -e MYSQL_ROOT_PASSWORD=1111
  wordpress:
    #depends_on ให้ wp ทำงานหนังจากที่ db ทำงานแล้ว
    depends_on:
      - db
    image: wordpress
    networks: 
      - wordpress
    ports: 
      - 888:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1111
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks: 
      - wordpress
    # restart ถ้ามี error ให้ Restart ตลอด
    restart: always
    ports: 
      - 8888:80


volumes: 
  db_data:

networks:
  wordpress: 



#docker-compose config [ เช็คไฟล์ Config ]
#docker-compose up [รันไฟล์]
#docker-compose down [ลบทั้งหมดที่อยุ่ใน docker-compose]